# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Shopify'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  raw_database: "EDM" #equivalent to project_id in BigQuery
    # Example Database name
  raw_schema: "EDM" #equivalent to dataset in BigQuery
    # Example Schema name

  get_brandname_from_tablename_flag: True
  # if get_brandname_from_tablename_flag = True, position of brand name in the daton integration name
  brandname_position_in_tablename: 0
  # if get_brandname_from_tablename_flag = False, provide the brand name to be populated in the table
  default_brandname: ""

  get_storename_from_tablename_flag: True    
  # if get_storename_from_tablename_flag = True, position of store name in the daton integration name
  storename_position_in_tablename: 1
  # if get_storename_from_tablename_flag = False, provide the store name to be populated in the table
  default_storename: ""

  currency_conversion_flag: False
  timezone_conversion_flag: False
  raw_table_timezone_offset_hours: {
    "Shopify.Raw.BRAND_UK_SHOPIFY_ABANDONED_CHECKOUTS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_BALANCE_TRANSACTIONS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_COLLECTS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_CUSTOM_COLLECTIONS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_CUSTOMERS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_DISPUTES":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_EVENTS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_FULFILLMENT_EVENTS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_FULFILLMENT_ORDERS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_GIFT_CARDS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_INVENTORY_ITEMS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_INVENTORY_LEVELS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_LOCATIONS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_ORDERS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_ORDERS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_POLICIES":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_PRICE_RULES":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_PRODUCT_METAFIELDS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_PRODUCTS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_REFUNDS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_SHOP":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_SMART_COLLECTIONS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_TENDER_TRANSACTIONS":-7,
    "Shopify.Raw.BRAND_UK_SHOPIFY_TRANSACTIONS":-7,
  }

  # Variables used for dbt-tests
  'dbt_date:time_zone': 'America/Los_Angeles'

      # Above are Example entries for raw table level input offset hours

  ShopifyAbandonedCheckouts: True
  ShopifyBalanceTransactions: True
  ShopifyCarrierServices: True
  ShopifyCollects: True
  ShopifyCountries: True
  ShopifyCustomCollections: True
  ShopifyCustomerAddress: True
  ShopifyCustomers: True
  ShopifyDisputes: True
  ShopifyEvents: True
  ShopifyFulfillmentEvents: True
  ShopifyFulfillmentOrders: True
  ShopifyGiftCards: True
  ShopifyInventoryItems: True
  ShopifyInventoryLevels: True
  ShopifyLocations: True
  ShopifyOrders: True
  ShopifyOrdersAddresses: True
  ShopifyOrdersCustomer: True
  ShopifyOrdersDiscountAllocations: True
  ShopifyOrdersDiscountApplications: True
  ShopifyOrdersFulfillments: True
  ShopifyOrdersLineItems: True
  ShopifyOrdersLineItemsTaxLines: True
  ShopifyOrdersShippingLines: True
  ShopifyPayouts: True
  ShopifyPolicies: True
  ShopifyPriceRules: True
  ShopifyProductMetafields: True
  ShopifyProducts: True
  ShopifyRefundLineItemsTax: True
  ShopifyRefundsLineItems: True
  ShopifyRefundsRefundLineItems: True
  ShopifyRefundsTransactions: True
  ShopifyShop: True
  ShopifySmartCollections: True
  ShopifyTenderTransactions: True
  ShopifyTransactions: True
  
# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  Shopify:
    Shopify:
      +schema: stg_shopify