edm_data_transformation:
  outputs:
    bigquery:
      dataset: edm
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: keyfile.json
      location: US
      method: service-account
      priority: interactive
      project: edm-saras
      threads: 4
      type: bigquery
    snowflake:
      type: snowflake
      account: HV65245.us-east-2.aws
      user: DATONDEVELOPER
      password: Developer01#!
      role: ACCOUNTADMIN
      database: EDM
      warehouse: COMPUTE_WH
      schema: EDM
      threads: 4
  target: bigquery
